FROM node:14
RUN apt-get update \
    && apt-get -y upgrade
# https://github.com/ohmyzsh/ohmyzsh#unattended-install
RUN sh -c "$(wget -O- https://github.com/deluan/zsh-in-docker/releases/download/v1.1.1/zsh-in-docker.sh)" -- \
    -t robbyrussell
RUN chsh -s $(which zsh)
CMD node